language: julia

os:
  - linux

julia:
  - 0.7
  # - 1.0
  # - nightly

notifications:
  email: false

# after_success:
#   - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
#   - julia --project=coverage/ coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 0.7
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project       -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project       docs/make.jl
after_success: skip